- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: memory_use
    - type: swap_free
    - type: swap_use
    - type: processor_use
    - type: processor_temperature