#################################################
# Motion
#################################################
- alias: Back Driveway Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.aarlo_motion_back_driveway
      from: "off"
      to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.back_driveway_floodlight
  condition:
    alias: "Sun down"
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: "below_horizon"

- alias: Back Driveway Idle
  trigger:
    - platform: state
      entity_id: binary_sensor.aarlo_motion_back_driveway
      to: "off"
      for: "00:10:00"
  action:
    - service: switch.turn_off
      entity_id: switch.back_driveway_floodlight
  
- alias: Pool Pump Control
  trigger:
    - platform: time
      at: '08:00:00'
    - platform: time
      at: '17:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: >
        {% set n = now() %}
        {% if n.hour >= 8 and n.hour < 17 %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.pool_pump