#################################################
# Door Open / Close
#################################################
- alias: Front Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.front_door_lights
  mode: single

- alias: Front Door Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: "off"
      for: "00:01:00"
  action:
    - service: light.turn_off
      entity_id: light.front_door_lights
  mode: single
