#######################
# Media Scenes
#######################
- alias: Plex Play
  trigger:
    - platform: state
      entity_id: media_player.living_room_plex
      from: idle
      to: playing
    - platform: state
      entity_id: media_player.living_room_plex
      from: paused
      to: playing
  condition: []
  action:
    - service: scene.turn_on
      entity_id: scene.movie_time
  mode: single

- alias: Plex Paused
  trigger:
    - platform: state
      entity_id: media_player.living_room_plex
      from: playing
      to: paused
  condition: []
  action:
    - service: scene.turn_on
      entity_id: scene.movie_time_paused
  mode: single

- alias: Kitchen Controller
  mode: queued
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 03f2a8fc68acb2cc66e1f44da37c3515
  action:
    - variables:
        command: "{{ trigger.event.data.command }}"
    - choose:
        - conditions:
            - "{{ command == 'on' }}"
          sequence:
            - service: light.toggle
              entity_id: light.kitchen_lights
        - conditions:
            - "{{ command == 'off' }}"
          sequence:
            - service: light.toggle
              entity_id: light.dining_room_lights
