#################################################
# carson-mac
#################################################
- alias: Office Carson Mac Screen On
  trigger:
    - platform: state
      entity_id: sensor.carson_mac_screen_off
      from: "True"
      to: "False"
  condition:
    condition: state
    entity_id:
      - media_player.office_tv
    state: "off"
  action:
    - service: tts.cloud_say
      entity_id: media_player.office_clock
      data:
        message: Hello Carson!
        options:
          gender: female
        language: en-GB
    - service: input_select.select_option
      data:
        option: active
      target:
        entity_id: input_select.office_state
  mode: single

- alias: Office Carson Mac Screen Off
  trigger:
    - platform: state
      entity_id: sensor.carson_mac_screen_off
      from: "False"
      to: "True"
      for: "00:30:00"
  condition:
    condition: state
    entity_id:
      - binary_sensor.office_motion_sensor_occupancy
    state: "off"
  action:
    - service: input_select.select_option
      data:
        option: inactive
      target:
        entity_id: input_select.office_state
  mode: single

- alias: Office Carson Mac Webcam On
  trigger:
    - platform: state
      entity_id: binary_sensor.carson_mac_camera_in_use
      to: "on"
  action:
    - service: input_select.select_option
      data:
        option: meeting
      target:
        entity_id: input_select.office_state
  mode: queued

- alias: Office Carson Mac Webcam Off
  trigger:
    - platform: state
      entity_id: binary_sensor.carson_mac_camera_in_use
      to: "off"
  action:
    - service: input_select.select_option
      data:
        option: active
      target:
        entity_id: input_select.office_state
  mode: queued

#################################################
# office-state
#################################################
- alias: Office State Active
  trigger:
    - platform: state
      entity_id: input_select.office_state
      from: "inactive"
      to: "active"
  action:
    - service: scene.turn_on
      entity_id: scene.office_active_day
  mode: queued

- alias: Office State Inactive
  trigger:
    - platform: state
      entity_id: input_select.office_state
      to: "inactive"
  action:
    - service: scene.turn_on
      entity_id: scene.office_inactive
  mode: queued

#################################################
# Motion
#################################################
- alias: Office Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_motion
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.office_lights

- alias: Office Vacant
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_occupancy
      to: "off"
      for: "00:15:00"
  condition:
    condition: state
    entity_id:
      - input_select.office_state 
    state: "inactive"
  action:
    - service: light.turn_off
      entity_id: light.office_lights

- alias: Office Bathroom Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.office_bathroom_occupancy
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.office_bathroom

- alias: Office Bathroom Vacant
  trigger:
    - platform: state
      entity_id: binary_sensor.office_bathroom_occupancy
      to: "off"
      for: "00:15:00"
  action:
    - service: light.turn_off
      entity_id: light.office_bathroom

- alias: Office Stairs Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.office_stairs_motion
      from: "off"
      to: "on"
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.office_state', 'meeting') }}"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                rgb_color: [255, 0, 0]
                entity_id: light.office_stairs
        - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.office_state', 'active') }}"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                rgb_color: [0, 255, 0]
                entity_id: light.office_stairs
      default:
        - service: light.turn_on
          data:
            brightness: 255
            rgb_color: [255, 255, 255]
            entity_id: light.office_stairs

- alias: Office Stairs Idle
  trigger:
    - platform: state
      entity_id: binary_sensor.office_stairs_motion
      to: "off"
      for: "00:2:00"
  action:
    - service: light.turn_off
      entity_id: light.office_stairs
